# Generated by Django 3.0.6 on 2020-07-25 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callnumber', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sound',
            old_name='sound',
            new_name='on',
        ),
    ]
